### ISSUE TITLE
Starting and Stopping Teleop Throws IllegalThreadStateException

### ISSUE THREAD

**Issue by mcoffin** [rmr662/RMR662-2013#6]
java.lang.IllegalThreadStateException
[cRIO]     in virtual method #12 of com.sun.squawk.VMThread(bci=10)
[cRIO]     at java.lang.Thread.start(215)
[cRIO]     at com.frc2013.rmr662.system.generic.Robot.operatorControl(Robot.java:49)
[cRIO]     at edu.wpi.first.wpilibj.SimpleRobot.startCompetition(SimpleRobot.java:145)
[cRIO]     at edu.wpi.first.wpilibj.RobotBase.startApp(RobotBase.java:169)
[cRIO]     in virtual method #10 of javax.microedition.midlet.MIDlet(bci=17)
[cRIO]     at javax.microedition.midlet.MIDletTunnelImpl.callStartApp(64)
[cRIO]     at com.sun.squawk.imp.MIDletMainWrapper.main(110)
[cRIO]     in virtual method #95 of com.sun.squawk.Klass(bci=25)
[cRIO]     at com.sun.squawk.Isolate.run(1506)
[cRIO]     at java.lang.Thread.run(231)
[cRIO]     in virtual method #47 of com.sun.squawk.VMThread(bci=42)
[cRIO]     in static method #3 of com.sun.squawk.VM(bci=6)

**Comment by mcoffin** [comment]
This was caused by the manner in which I went about fixing a problem. Commit has been reverted. Closed. Re-opens #5.
